# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            GitHub Tutorial
tagline:          'An introduction'
description:      'Presented at the Digital Ottoman Platform Workshop'

author:
  name:           'Jeremy Guillette'

paginate:         5

# Custom vars
version:          0.1

github:
  repo:           https://github.com/jaguillette/github_tutorial
